//! Rust emit: writes `_generated.rs` (axum router + event emitters).

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use super::config::Config;
use super::model::{Api, ConnInject, EventApi, RawApi};
use super::types::result_ok_type;
use super::util::{capitalize, last_path_segment, snake_to_camel};
use super::writer::Writer;

// `include_generated!(MyState, MyBus)` wraps the include in a module
// that aliases these internal names to the caller's actual types, so
// the emitted file doesn't need to know where the state lives.
const STATE_TY: &str = "__DraadState";
const BUS_TY: &str = "__DraadBus";

pub(super) fn render_generated_rs(
    cfg: &Config,
    apis: &[Api],
    event_apis: &[EventApi],
    raw_apis: &[RawApi],
    ty_modules: &[String],
) -> String {
    let mut w = Writer::new("    ");

    let any_conn = apis.iter().any(|a| {
        a.methods
            .iter()
            .any(|m| m.params.iter().any(|p| p.conn.is_some()))
    });
    write_header(&mut w, cfg, any_conn);
    write_module_uses(&mut w, cfg, apis, event_apis, ty_modules);

    for api in apis {
        for method in &api.methods {
            write_method_args_struct(&mut w, method);
            write_method_handler(&mut w, api, method);
        }
    }

    write_rpc_router(&mut w, apis);
    write_event_emitters(&mut w, event_apis);
    write_url_consts(&mut w, raw_apis);

    w.into_string()
}

pub(super) fn write_generated_rs(
    cfg: &Config,
    out_path: &Path,
    apis: &[Api],
    event_apis: &[EventApi],
    raw_apis: &[RawApi],
    ty_modules: &[String],
) -> std::io::Result<()> {
    let out = render_generated_rs(cfg, apis, event_apis, raw_apis, ty_modules);
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    if let Ok(existing) = fs::read_to_string(out_path) {
        if existing == out {
            return Ok(());
        }
    }
    fs::write(out_path, out)
}

fn write_header(w: &mut Writer, _cfg: &Config, any_conn: bool) {
    w.line("// Generated by draad-codegen. Do not edit.");
    w.line("// Include via `draad::include_generated!(StateTy, BusTy)`.");
    w.blank();
    w.line("use axum::extract::{Query, State};");
    w.line("use axum::routing::{delete, get, patch, post, put};");
    w.line("use axum::{Json, Router};");
    if any_conn {
        // `conn: &Conn` handlers resolve the caller via `Caller` and return a
        // `Response`, so the missing-connection case can short-circuit without
        // touching the user's error type.
        w.line("use axum::response::IntoResponse;");
        w.line("use draad::runtime::Caller;");
    }
    w.blank();
}

fn write_module_uses(
    w: &mut Writer,
    cfg: &Config,
    apis: &[Api],
    event_apis: &[EventApi],
    ty_modules: &[String],
) {
    let mut modules: BTreeSet<&str> = BTreeSet::new();
    for api in apis {
        modules.insert(api.module.as_str());
    }
    for ev in event_apis {
        modules.insert(ev.module.as_str());
    }
    // Include modules that only host `#[ty]` types (e.g. a shared
    // `error.rs`) — the generated handler signatures reference those
    // names, so they need to be in scope.
    for module in ty_modules {
        modules.insert(module.as_str());
    }
    for module in &modules {
        w.line(&format!(
            "use {prefix}::{module}::*;",
            prefix = cfg.api_modules_prefix
        ));
    }
    if !modules.is_empty() {
        w.blank();
    }
}

fn write_method_args_struct(w: &mut Writer, m: &super::model::Method) {
    let wire: Vec<&super::model::Param> = m.params.iter().filter(|p| p.conn.is_none()).collect();
    if wire.is_empty() {
        return;
    }
    w.line("#[derive(::serde::Deserialize)]");
    w.line(&format!("struct __{cmd}_args {{", cmd = m.command));
    w.indented(|w| {
        for p in &wire {
            w.line(&format!("{}: {},", p.name, p.rust_type));
        }
    });
    w.line("}");
    w.blank();
}

fn write_method_handler(w: &mut Writer, api: &Api, m: &super::model::Method) {
    let wire: Vec<&super::model::Param> = m.params.iter().filter(|p| p.conn.is_none()).collect();
    let has_conn = m.params.iter().any(|p| p.conn.is_some());
    let needs_required_conn = m
        .params
        .iter()
        .any(|p| matches!(p.conn, Some(ConnInject { required: true })));

    let mut extractors = vec![format!("State(__ctx): State<{STATE_TY}>")];
    // `Caller` is a FromRequestParts extractor, so it must precede the body.
    if has_conn {
        extractors.push("__caller: Caller".to_string());
    }
    if !wire.is_empty() {
        // Body verbs (POST/PUT/PATCH) take args as a JSON body; non-body
        // verbs (GET/DELETE) take the same args off the query string.
        // The DTO is the same `__{cmd}_args` struct either way.
        let inner = format!("__{cmd}_args", cmd = m.command);
        extractors.push(if m.verb.has_body() {
            format!("Json(__args): Json<{inner}>")
        } else {
            format!("Query(__args): Query<{inner}>")
        });
    }

    // Build the call argument list in the method's original parameter order,
    // interleaving wire args (`__args.x`) with injected connections.
    let call_args = {
        let parts: Vec<String> = m
            .params
            .iter()
            .map(|p| match p.conn {
                None => format!("__args.{}", p.name),
                Some(ConnInject { required: true }) => "__conn".to_string(),
                Some(ConnInject { required: false }) => "__caller.0.as_ref()".to_string(),
            })
            .collect();
        if parts.is_empty() {
            String::new()
        } else {
            format!(", {}", parts.join(", "))
        }
    };

    let call = format!(
        "<{STATE_TY} as {trait_name}>::{method}(&__ctx{call_args}).await",
        trait_name = api.class_name,
        method = m.rust_name,
    );

    if has_conn {
        // Conn-injecting handlers return a `Response`: a required `&Conn`
        // short-circuits with 409 when the caller has no live socket, while
        // the Ok/Err arms still flow through the user's `IntoResponse`.
        w.line(&format!(
            "async fn __{cmd}({extractors}) -> axum::response::Response {{",
            cmd = m.command,
            extractors = extractors.join(", "),
        ));
        w.indented(|w| {
            if needs_required_conn {
                w.line("let Some(__conn) = __caller.0.as_ref() else {");
                w.indented(|w| {
                    w.line(
                        "return (axum::http::StatusCode::CONFLICT, \
                         \"draad: no live connection for this client\").into_response();",
                    );
                });
                w.line("};");
            }
            let body = if m.returns_result {
                format!("{call}.map(Json).into_response()")
            } else {
                format!("Json({call}).into_response()")
            };
            w.line(&body);
        });
        w.line("}");
        w.blank();
        return;
    }

    // ── No injected conn: original handler shape (kept byte-identical) ──
    //
    // We lean on axum's `IntoResponse` machinery instead of a shim of
    // our own: `Json<T>` → 200 + JSON body for the Ok side, the user's
    // error type's `IntoResponse` impl picks the status + body for the
    // Err side. Errors must implement `axum::response::IntoResponse`.
    let ok = result_ok_type(m.returns_result, &m.ret_rust);
    let return_ty = match (m.returns_result, m.err_rust.as_deref()) {
        (true, Some(err)) => format!("Result<Json<{ok}>, {err}>"),
        (true, None) => format!("Result<Json<{ok}>, ()>"), // shouldn't happen
        (false, _) => format!("Json<{ok}>"),
    };
    let body = if m.returns_result {
        format!("{call}.map(Json)")
    } else {
        format!("Json({call})")
    };

    w.line(&format!(
        "async fn __{cmd}({extractors}) -> {return_ty} {{",
        cmd = m.command,
        extractors = extractors.join(", "),
    ));
    w.indented(|w| {
        w.line(&body);
    });
    w.line("}");
    w.blank();
}

fn write_rpc_router(w: &mut Writer, apis: &[Api]) {
    w.line(&format!("pub fn rpc_router() -> Router<{STATE_TY}> {{"));
    w.indented(|w| {
        w.line("Router::new()");
        w.indented(|w| {
            for api in apis {
                for m in &api.methods {
                    w.line(&format!(
                        ".route(\"/{ns}/{name}\", {verb_fn}(__{cmd}))",
                        ns = api.namespace,
                        name = m.rust_name,
                        verb_fn = m.verb.axum_fn(),
                        cmd = m.command,
                    ));
                }
            }
        });
    });
    w.line("}");
    w.blank();
}

fn write_event_emitters(w: &mut Writer, event_apis: &[EventApi]) {
    for ev in event_apis {
        let pascal = capitalize(&snake_to_camel(&ev.namespace));
        w.line("#[derive(Clone)]");
        w.line(&format!("pub struct {pascal}Emitter {{ bus: {BUS_TY} }}"));
        w.blank();
        w.line(&format!("impl {pascal}Emitter {{"));
        w.indented(|w| {
            for e in &ev.events {
                let payload = last_path_segment(&e.payload_rust);
                w.line(&format!(
                    "/// Publishes the `{wire}` event to all WS subscribers.",
                    wire = e.wire
                ));
                w.line(&format!(
                    "pub fn emit_{name}(&self, payload: &{payload}) {{",
                    name = e.rust_name,
                ));
                w.indented(|w| {
                    w.line(&format!(
                        "self.bus.publish(\"{wire}\", payload);",
                        wire = e.wire
                    ));
                });
                w.line("}");
            }
        });
        w.line("}");
        w.blank();
    }

    w.line("#[derive(Clone)]");
    w.line("pub struct Events {");
    w.indented(|w| {
        for ev in event_apis {
            let pascal = capitalize(&snake_to_camel(&ev.namespace));
            w.line(&format!("pub {ns}: {pascal}Emitter,", ns = ev.namespace));
        }
    });
    w.line("}");
    w.blank();

    w.line("impl Events {");
    w.indented(|w| {
        let bus_param = if event_apis.is_empty() { "_bus" } else { "bus" };
        w.line(&format!("pub fn new({bus_param}: {BUS_TY}) -> Self {{"));
        w.indented(|w| {
            w.line("Self {");
            w.indented(|w| {
                for ev in event_apis {
                    let pascal = capitalize(&snake_to_camel(&ev.namespace));
                    w.line(&format!(
                        "{ns}: {pascal}Emitter {{ bus: bus.clone() }},",
                        ns = ev.namespace
                    ));
                }
            });
            w.line("}");
        });
        w.line("}");
    });
    w.line("}");
}

/// Emit a `pub mod urls { pub const … }` of path templates for every `#[raw]`
/// endpoint, so the consumer can mount its Axum routes against the same string
/// the TS URL-builders use. A no-op (nothing emitted) when there are no raw
/// endpoints, keeping existing generated output byte-identical.
fn write_url_consts(w: &mut Writer, raw_apis: &[RawApi]) {
    if raw_apis.iter().all(|r| r.methods.is_empty()) {
        return;
    }
    w.line("pub mod urls {");
    w.indented(|w| {
        for raw in raw_apis {
            for m in &raw.methods {
                // Rust method idents are already snake_case, so uppercasing
                // yields SCREAMING_SNAKE; `{:?}` emits an escaped &str literal.
                w.line(&format!(
                    "pub const {konst}: &str = {path:?};",
                    konst = m.rust_name.to_uppercase(),
                    path = m.path_template,
                ));
            }
        }
    });
    w.line("}");
    w.blank();
}
