//! TypeScript emit: writes a single `index.ts` containing the transport
//! interface, every wire type, the per-namespace classes, and the `Api`
//! aggregator.

use std::fs;
use std::path::Path;

use super::model::{Api, EventApi, Param, PathSeg, RawApi, Verb};
use super::ty_decl::emit_ty_decl;
use super::types::is_numeric_rust;
use super::util::{capitalize, snake_to_camel};
use super::writer::Writer;

/// Transport interface, error type, and a default REST+WS `Rpc`
/// implementation embedded at the top of every generated `index.ts`.
///
/// Source lives in `rpc_runtime.ts` next to this file — edit it there
/// and rely on syntax highlighting / formatters instead of escaping the
/// file into a Rust string literal.
const RPC_RUNTIME_TS: &str = include_str!("rpc_runtime.ts");

pub(super) fn render_index(
    ty_items: &[&syn::Item],
    apis: &[Api],
    event_apis: &[EventApi],
    raw_apis: &[RawApi],
) -> String {
    let mut w = Writer::new("\t");

    // Order: header → user surface (types, namespace classes, the `Api`
    // aggregator) → runtime defaults (`Rpc` interface, `RpcError`,
    // `defaultRpc`). TypeScript hoists `type`/`interface`/`class`
    // declarations for type-position references, so the API classes
    // citing `Rpc` and `RpcError` before they're lexically declared is
    // safe. The runtime block sits at the bottom because it's machine-
    // generated noise readers don't need to scroll past to find their
    // own types.
    w.line("// Generated by draad-codegen. Do not edit.");

    render_ty_decls(&mut w, ty_items);

    for api in apis {
        write_api_class(&mut w, api);
    }
    for ev in event_apis {
        write_events_class(&mut w, ev);
    }
    for raw in raw_apis {
        write_urls_class(&mut w, raw);
    }

    write_aggregator(&mut w, apis, event_apis, raw_apis);

    w.blank();
    w.raw(RPC_RUNTIME_TS);

    w.into_string()
}

pub(super) fn write_index(
    out_path: &Path,
    ty_items: &[&syn::Item],
    apis: &[Api],
    event_apis: &[EventApi],
    raw_apis: &[RawApi],
) -> std::io::Result<()> {
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    let out = render_index(ty_items, apis, event_apis, raw_apis);
    // Skip the write if the file already matches — otherwise we'd bump
    // its mtime on every build, which combined with the
    // `cargo:rerun-if-changed=index.ts` directive emit_cargo_directives
    // prints would trap the build script in an infinite re-run loop.
    if let Ok(existing) = fs::read_to_string(out_path) {
        if existing == out {
            return Ok(());
        }
    }
    fs::write(out_path, out)
}

/// Render every `#[ty]` item as an `export type ...;` declaration
/// directly from its `syn::Item`. Each block is preceded by a separator
/// blank line so the output reads like the previous ts-rs-driven shape.
fn render_ty_decls(w: &mut Writer, ty_items: &[&syn::Item]) {
    for item in ty_items {
        w.blank();
        let rendered = emit_ty_decl(item);
        // The renderer already manages its own indentation; splice in
        // verbatim at column 0 rather than letting the Writer's indent
        // level re-indent.
        w.raw(&rendered);
    }
}

fn write_api_class(w: &mut Writer, api: &Api) {
    w.blank();
    write_jsdoc(w, &api.docs);
    w.line(&format!("export class {} {{", api.class_name));
    w.indented(|w| {
        w.line("constructor(private rpc: Rpc) {}");
        for m in &api.methods {
            write_api_method(w, api, m);
        }
    });
    w.line("}");
}

fn write_api_method(w: &mut Writer, api: &Api, m: &super::model::Method) {
    // Injected `conn: &Conn` params are server-filled — they never appear in
    // the client signature or the args object.
    let wire: Vec<&super::model::Param> = m.params.iter().filter(|p| p.conn.is_none()).collect();
    let param_decl = wire
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ts_type))
        .collect::<Vec<_>>()
        .join(", ");

    // POST is the implicit default so emit `call("ns/name", { args })`
    // verbatim — keeps existing generated TS byte-identical. For other
    // verbs we always pass an args object (even `{}`) so the verb sits
    // in the third slot.
    let args_obj = if wire.is_empty() {
        "{}".to_string()
    } else {
        let names = wire
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        format!("{{ {names} }}")
    };
    let call_tail = if m.verb == Verb::Post {
        if wire.is_empty() {
            String::new()
        } else {
            format!(", {args_obj}")
        }
    } else {
        format!(", {args_obj}, \"{verb}\"", verb = m.verb.ts_label())
    };

    w.blank();
    write_method_jsdoc(w, &m.docs, &m.params, m.err_ts.as_deref());
    w.line(&format!(
        "{name}({decl}): Promise<{ret}> {{",
        name = m.ts_name,
        decl = param_decl,
        ret = m.ret_ts,
    ));
    w.indented(|w| {
        w.line(&format!(
            "return this.rpc.call(\"{ns}/{name}\"{call_tail});",
            ns = api.namespace,
            name = m.rust_name,
        ));
    });
    w.line("}");
}

/// A no-ctor class of pure URL-builders for a `#[raw]` trait. Aggregated on
/// the `Api` as `api.urls`.
fn write_urls_class(w: &mut Writer, raw: &RawApi) {
    w.blank();
    write_jsdoc(w, &raw.docs);
    w.line(&format!("export class {} {{", raw.class_name));
    w.indented(|w| {
        for m in &raw.methods {
            write_url_method(w, m);
        }
    });
    w.line("}");
}

fn write_url_method(w: &mut Writer, m: &super::model::RawEndpoint) {
    let param_decl = m
        .params
        .iter()
        .map(|p| format!("{}: {}", snake_to_camel(&p.name), p.ts_type))
        .collect::<Vec<_>>()
        .join(", ");

    // Build the template literal from the parsed segments: static text
    // verbatim, `{name}` String → encodeURIComponent, numeric / catch-all → raw.
    let mut body = String::new();
    for seg in &m.segments {
        match seg {
            PathSeg::Static(s) => body.push_str(s),
            PathSeg::Param { name, catch_all } => {
                let camel = snake_to_camel(name);
                let numeric = m
                    .params
                    .iter()
                    .find(|p| &p.name == name)
                    .is_some_and(|p| is_numeric_rust(&p.rust_type));
                if *catch_all || numeric {
                    body.push_str(&format!("${{{camel}}}"));
                } else {
                    body.push_str(&format!("${{encodeURIComponent({camel})}}"));
                }
            }
        }
    }

    w.blank();
    write_method_jsdoc(w, &m.docs, &m.params, None);
    w.line(&format!(
        "{name}({decl}): string {{",
        name = m.ts_name,
        decl = param_decl,
    ));
    w.indented(|w| {
        w.line(&format!("return `{body}`;"));
    });
    w.line("}");
}

fn write_events_class(w: &mut Writer, ev: &EventApi) {
    w.blank();
    write_jsdoc(w, &ev.docs);
    w.line(&format!("export class {} {{", ev.class_name));
    w.indented(|w| {
        w.line("constructor(private rpc: Rpc) {}");
        for e in &ev.events {
            w.blank();
            write_jsdoc(w, &e.docs);
            w.line(&format!(
                "on{cap}(handler: (payload: {pl}) => void): UnlistenFn {{",
                cap = capitalize(&e.ts_name),
                pl = e.payload_ts,
            ));
            w.indented(|w| {
                w.line(&format!(
                    "return this.rpc.listen<{pl}>(\"{wire}\", handler);",
                    pl = e.payload_ts,
                    wire = e.wire,
                ));
            });
            w.line("}");
        }
    });
    w.line("}");
}

fn write_aggregator(w: &mut Writer, apis: &[Api], event_apis: &[EventApi], raw_apis: &[RawApi]) {
    w.blank();
    w.line("export class Api {");
    w.indented(|w| {
        for api in apis {
            write_jsdoc(w, &api.docs);
            w.line(&format!(
                "{ns}: {cls};",
                ns = api.namespace,
                cls = api.class_name
            ));
        }
        for ev in event_apis {
            write_jsdoc(w, &ev.docs);
            w.line(&format!(
                "{ns}Events: {cls};",
                ns = ev.namespace,
                cls = ev.class_name
            ));
        }
        for raw in raw_apis {
            write_jsdoc(w, &raw.docs);
            w.line(&format!("urls: {cls};", cls = raw.class_name));
        }
        w.blank();
        w.line("constructor(private rpc: Rpc) {");
        w.indented(|w| {
            for api in apis {
                w.line(&format!(
                    "this.{ns} = new {cls}(rpc);",
                    ns = api.namespace,
                    cls = api.class_name
                ));
            }
            for ev in event_apis {
                w.line(&format!(
                    "this.{ns}Events = new {cls}(rpc);",
                    ns = ev.namespace,
                    cls = ev.class_name
                ));
            }
            // URL-builders are pure string helpers — no transport needed.
            for raw in raw_apis {
                w.line(&format!("this.urls = new {cls}();", cls = raw.class_name));
            }
        });
        w.line("}");
        w.blank();
        w.line("/**");
        w.line(" * Subscribe to every failed RPC call from this `Api`.");
        w.line(" * The handler fires *before* the promise rejects, so local");
        w.line(" * `try { ... } catch (e)` blocks still see the error too.");
        w.line(" * Returns an unsubscribe handle, or a no-op if the underlying");
        w.line(" * transport does not implement `onError`.");
        w.line(" */");
        w.line("onError(handler: (err: RpcError) => void): UnlistenFn {");
        w.indented(|w| {
            w.line("return this.rpc.onError?.(handler) ?? (() => {});");
        });
        w.line("}");
    });
    w.line("}");
}

fn write_jsdoc(w: &mut Writer, docs: &[String]) {
    if docs.is_empty() {
        return;
    }
    if docs.len() == 1 {
        w.line(&format!("/** {} */", docs[0]));
        return;
    }
    w.line("/**");
    for line in docs {
        w.line(&format!(" * {line}"));
    }
    w.line(" */");
}

fn write_method_jsdoc(
    w: &mut Writer,
    method_docs: &[String],
    params: &[Param],
    err_ts: Option<&str>,
) {
    let has_method = !method_docs.is_empty();
    let has_params = params
        .iter()
        .any(|p| p.conn.is_none() && !p.docs.is_empty());
    let has_throws = err_ts.is_some();
    if !has_method && !has_params && !has_throws {
        return;
    }
    if has_method && !has_params && !has_throws && method_docs.len() == 1 {
        w.line(&format!("/** {} */", method_docs[0]));
        return;
    }
    w.line("/**");
    for line in method_docs {
        w.line(&format!(" * {line}"));
    }
    for p in params {
        if p.conn.is_some() || p.docs.is_empty() {
            continue;
        }
        let summary = p.docs.join(" ");
        w.line(&format!(" * @param {} - {summary}", p.name));
    }
    if let Some(err) = err_ts {
        w.line(&format!(" * @throws {{RpcError<{err}>}}"));
    }
    w.line(" */");
}
