// Generated by draad-codegen. Do not edit.

export type ApiError = "EmptyName" | "Overflow";

/** One connected participant, as seen by everyone else. */
export type Member = { name: string, };

/** A chat line relayed to every subscriber of `presence/said`. */
export type ChatLine = { from: string, text: string, };

/** A running counter, demoing mutable state + server-pushed events. */
export class CounterApi {
	constructor(private rpc: Rpc) {}

	/** Current value. */
	current(): Promise<number> {
		return this.rpc.call("counter/current");
	}

	/**
	 * Increment by one and return the new value. Also publishes a
	 * `counter/changed` event so subscribers can update in real time.
	 */
	increment(): Promise<number> {
		return this.rpc.call("counter/increment");
	}
}

export class GreetApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Returns a personalized greeting. Errors with `EmptyName` if the
	 * input is blank.
	 * @throws {RpcError<ApiError>}
	 */
	hello2(name: string): Promise<string> {
		return this.rpc.call("greet/hello2", { name });
	}

	/**
	 * Adds two numbers. Errors with `Overflow` if `a + b` doesn't fit
	 * in an `i32`.
	 * @throws {RpcError<ApiError>}
	 */
	add(a: number, b: number): Promise<number> {
		return this.rpc.call("greet/add", { a, b });
	}

	/**
	 * Demonstrates injecting the caller's live connection into an HTTP
	 * handler: returns the server-assigned `client_id` and pushes a
	 * `greet/pong` frame down the *same* client's WebSocket. The generated
	 * TS is `whoami(): Promise<string>` — the `conn` param is server-filled.
	 * 409s if the caller has no live socket.
	 * @throws {RpcError<ApiError>}
	 */
	whoami(): Promise<string> {
		return this.rpc.call("greet/whoami");
	}
}

/** Server-pushed events for the counter namespace. */
export class CounterEvents {
	constructor(private rpc: Rpc) {}

	/** Fired after every successful `increment`. */
	onChanged(handler: (payload: number) => void): UnlistenFn {
		return this.rpc.listen<number>("counter/changed", handler);
	}
}

/**
 * Server-pushed events for the presence namespace. These generate typed
 * `*Emitter` methods on the Rust side and `on{Event}` listeners on the TS
 * client.
 */
export class PresenceEvents {
	constructor(private rpc: Rpc) {}

	/**
	 * Full roster, re-broadcast whenever someone joins or leaves.
	 * Topic: `presence/roster`.
	 */
	onRoster(handler: (payload: Member[]) => void): UnlistenFn {
		return this.rpc.listen<Member[]>("presence/roster", handler);
	}

	/** A chat line from one participant. Topic: `presence/said`. */
	onSaid(handler: (payload: ChatLine) => void): UnlistenFn {
		return this.rpc.listen<ChatLine>("presence/said", handler);
	}
}

export class Urls {

	/**
	 * A downloadable asset. `{*path}` is a catch-all (holds slashes), so it's
	 * interpolated raw rather than URL-encoded.
	 */
	file(path: string): string {
		return `/files/${path}`;
	}

	/**
	 * A user's avatar at a given size. `id` (numeric) is interpolated raw;
	 * `size` (string) is `encodeURIComponent`'d.
	 */
	avatar(id: number, size: string): string {
		return `/avatar/${id}/${encodeURIComponent(size)}`;
	}
}

export class Api {
	/** A running counter, demoing mutable state + server-pushed events. */
	counter: CounterApi;
	greet: GreetApi;
	/** Server-pushed events for the counter namespace. */
	counterEvents: CounterEvents;
	/**
	 * Server-pushed events for the presence namespace. These generate typed
	 * `*Emitter` methods on the Rust side and `on{Event}` listeners on the TS
	 * client.
	 */
	presenceEvents: PresenceEvents;
	urls: Urls;

	constructor(private rpc: Rpc) {
		this.counter = new CounterApi(rpc);
		this.greet = new GreetApi(rpc);
		this.counterEvents = new CounterEvents(rpc);
		this.presenceEvents = new PresenceEvents(rpc);
		this.urls = new Urls();
	}

	/**
	 * Subscribe to every failed RPC call from this `Api`.
	 * The handler fires *before* the promise rejects, so local
	 * `try { ... } catch (e)` blocks still see the error too.
	 * Returns an unsubscribe handle, or a no-op if the underlying
	 * transport does not implement `onError`.
	 */
	onError(handler: (err: RpcError) => void): UnlistenFn {
		return this.rpc.onError?.(handler) ?? (() => {});
	}
}

/** Returned by `Rpc.listen`, call to unsubscribe. */
export type UnlistenFn = () => void;

/** HTTP verb a generated method maps to. */
export type HttpVerb = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/**
 * Transport contract the generated API classes call into. Implement this
 * in your app (using fetch / axios / tauri / etc.) and pass it to
 * `new Api(rpc)`. Or use `defaultRpc(...)` below.
 */
export interface Rpc {
	/**
	 * Send an RPC request. The wire command is `{namespace}/{method}`.
	 * Verb defaults to POST (body-bearing); GET/DELETE callers must pass
	 * the verb explicitly so `args` is serialised as a query string.
	 */
	call<T>(command: string, args?: Record<string, unknown>, method?: HttpVerb): Promise<T>;

	/** Subscribe to a backend event. Returns an unsubscribe handle. */
	listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn;

	/**
	 * Run `handler` every time the event socket (re)connects, *after* live
	 * subscriptions have been restored. Use it to re-establish per-session
	 * state on the server (e.g. re-announce presence). Optional on the
	 * interface — custom transports can omit it.
	 */
	onOpen?(handler: () => void): UnlistenFn;

	/**
	 * Send a raw application frame to the server over the event socket —
	 * e.g. a presence announce or a client→client publish. The shape is
	 * app-defined; draad reserves only `{type:"subscribe"|"unsubscribe"}`.
	 * Connects the socket on demand and buffers until it's open. Optional
	 * on the interface.
	 */
	send?(frame: Record<string, unknown>): void;

	/**
	 * Subscribe to every failed RPC call. The handler fires *before* the
	 * promise rejects, so local `try { ... } catch (e)` paths still see
	 * the error too. Useful for global concerns: toast on error, route
	 * 401s to a sign-in flow, ship a Sentry breadcrumb, etc. Optional on
	 * the interface — custom transports can omit it.
	 */
	onError?(handler: (err: RpcError) => void): UnlistenFn;
}

/**
 * Thrown (or returned) by `Rpc.call` implementations on failure.
 *
 * The generic `E` is the shape of the server's error body — generated
 * methods tag their `@throws` with the concrete error type pulled from
 * the trait's `Result<_, E>` return.
 */
export class RpcError<E = unknown> extends Error {
	constructor(
		public readonly code: string,
		/** HTTP status code from the response (or 0 if the request never reached the server). */
		public readonly status: number,
		/**
		 * Parsed JSON body from the server, when present. Falls back to
		 * the raw response text on non-JSON responses, and to `null`
		 * when the body was empty.
		 */
		public readonly body: E | string | null,
		message: string,
	) {
		super(message);
		this.name = "RpcError";
	}
}

/**
 * A connected client: the unified transport handle returned by
 * {@link defaultRpc}. `call` rides HTTP; `listen` / `send` / events ride the
 * WebSocket channel. Carries the server-assigned {@link Conn.id} that ties the
 * two together.
 */
export interface Conn extends Rpc {
	/**
	 * Server-assigned, reconnect-stable client id. `null` until the first
	 * `$draad/welcome` frame arrives after the initial connect; stable across
	 * reconnects thereafter. Sent as the `x-draad-client` header on every
	 * `call` and as `?resume=` on WebSocket reconnects.
	 */
	readonly id: string | null;
}

export type DefaultRpcOptions = {
	/** Base URL for RPC calls. Requests go to `${baseUrl}/${command}`. */
	baseUrl?: string;
	/** WebSocket URL for events. Omit to make `listen()` throw. */
	wsUrl?: string;
	/** Extra headers added to every RPC call. */
	headers?: Record<string, string>;
	/** Disable WebSocket auto-reconnect. Default: true. */
	reconnect?: boolean;
	/** Cap on the backoff between reconnect attempts. Default: 30000. */
	maxReconnectDelayMs?: number;
};

/**
 * Default `Rpc` implementation: POST JSON for calls, a shared WebSocket
 * for events. Wire format:
 *
 *  - Calls: `POST {baseUrl}/{command}` with body `args`. 2xx responses
 *    are parsed as JSON and returned; non-2xx are thrown as `RpcError`.
 *  - Events: WS frames shaped `{ topic: string, payload: T }`.
 *
 * Auto-reconnects with exponential backoff + jitter (capped at
 * `maxReconnectDelayMs`) as long as there are active subscribers. Replace
 * with your own `Rpc` for auth, custom transports, or a different wire
 * format.
 */
export function defaultRpc(opts: DefaultRpcOptions = {}): Conn {
	const baseUrl = opts.baseUrl ?? "/api";
	const maxDelayMs = opts.maxReconnectDelayMs ?? 30000;
	const shouldReconnect = opts.reconnect !== false;
	const subs = new Map<string, Set<(payload: unknown) => void>>();
	const errorHandlers = new Set<(err: RpcError) => void>();
	const openHandlers = new Set<() => void>();
	// Frames requested via `send()` before the socket was open; flushed on open.
	const pendingSends: string[] = [];
	let ws: WebSocket | undefined;
	let reconnectDelayMs = 500;
	let reconnectTimer: ReturnType<typeof setTimeout> | undefined;

	// Server-assigned identity, persisted so it survives reloads and is
	// replayed (HTTP header + WS `?resume=`) to tie calls to the socket.
	const CLIENT_KEY = "draad.client";
	let clientId: string | null = readStoredClientId();

	function readStoredClientId(): string | null {
		try {
			return typeof sessionStorage !== "undefined" ? sessionStorage.getItem(CLIENT_KEY) : null;
		} catch { return null; }
	}
	function setClientId(id: unknown): void {
		if (typeof id !== "string" || !id || id === clientId) return;
		clientId = id;
		try { sessionStorage.setItem(CLIENT_KEY, id); } catch { /* ignore */ }
	}

	function fireError(err: RpcError): RpcError {
		// Notify every observer; a single throwing handler must not
		// take out the others, hence the per-handler try/catch.
		for (const h of errorHandlers) {
			try { h(err); } catch { /* swallow handler errors */ }
		}
		return err;
	}

	function flushPending(): void {
		if (!ws || ws.readyState !== WebSocket.OPEN) return;
		for (const frame of pendingSends.splice(0)) ws.send(frame);
	}

	function rawSend(frame: Record<string, unknown>): void {
		ensureWs();
		pendingSends.push(JSON.stringify(frame));
		flushPending();
	}

	function resumeUrl(): string {
		const base = opts.wsUrl!;
		if (!clientId) return base;
		return base + (base.includes("?") ? "&" : "?") + "resume=" + encodeURIComponent(clientId);
	}

	function openWs(): WebSocket {
		const sock = new WebSocket(resumeUrl());
		// Fire onOpen handlers exactly once per socket. On a fresh connect we
		// wait for the `$draad/welcome` frame first so handlers can read
		// `conn.id`; on a resume the id is already known, so fire on open.
		let firedOpen = false;
		const fireOpen = () => {
			if (firedOpen) return;
			firedOpen = true;
			for (const h of openHandlers) {
				try { h(); } catch { /* swallow handler errors */ }
			}
		};
		sock.addEventListener("open", () => {
			reconnectDelayMs = 500;
			// Restore every live subscription, then flush queued sends.
			for (const topic of subs.keys()) sock.send(JSON.stringify({ type: "subscribe", topic }));
			flushPending();
			if (clientId) fireOpen();
		});
		sock.addEventListener("message", (ev) => {
			try {
				const { topic, payload } = JSON.parse(String(ev.data));
				// draad's control frame: learn (or confirm) our id, then —
				// on a fresh connect — release the deferred onOpen handlers.
				if (topic === "$draad/welcome") {
					setClientId(payload?.clientId);
					fireOpen();
					return;
				}
				subs.get(topic)?.forEach((h) => h(payload));
			} catch {
				/* ignore malformed frames */
			}
		});
		sock.addEventListener("close", () => {
			ws = undefined;
			if (!shouldReconnect || subs.size === 0) return;
			const base = Math.min(reconnectDelayMs, maxDelayMs);
			const jitter = base * (0.8 + Math.random() * 0.4);
			reconnectDelayMs = Math.min(reconnectDelayMs * 2, maxDelayMs);
			reconnectTimer = setTimeout(() => {
				reconnectTimer = undefined;
				if (subs.size > 0 && !ws) ws = openWs();
			}, jitter);
		});
		return sock;
	}

	function ensureWs(): WebSocket {
		if (!opts.wsUrl) {
			throw new RpcError("NO_WS_URL", 0, null, "defaultRpc: wsUrl not configured; cannot listen()");
		}
		if (ws && ws.readyState !== WebSocket.CLOSED) return ws;
		ws = openWs();
		return ws;
	}

	return {
		get id(): string | null {
			return clientId;
		},
		async call<T>(command: string, args?: Record<string, unknown>, method: HttpVerb = "POST"): Promise<T> {
			const hasBody = method === "POST" || method === "PUT" || method === "PATCH";
			let url = `${baseUrl}/${command}`;
			const headers: Record<string, string> = { ...opts.headers };
			// Replay our identity so the server can tie this call to our socket.
			if (clientId) headers["x-draad-client"] = clientId;
			const init: RequestInit = { method, headers };
			if (hasBody) {
				(init.headers as Record<string, string>)["Content-Type"] = "application/json";
				init.body = JSON.stringify(args ?? {});
			} else if (args) {
				const params = new URLSearchParams();
				for (const [k, v] of Object.entries(args)) {
					if (v === undefined || v === null) continue;
					if (Array.isArray(v)) {
						for (const item of v) params.append(k, String(item));
					} else {
						params.append(k, String(v));
					}
				}
				const qs = params.toString();
				if (qs) url += `?${qs}`;
			}
			// Every failure path constructs an `RpcError`, fires the
			// global `onError` observers, then throws — so callers'
			// local try/catch and global handlers both see it.
			let res: Response;
			try {
				res = await fetch(url, init);
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("NETWORK", 0, null, msg));
			}
			if (!res.ok) {
				// Best effort at giving callers the typed body their
				// `@throws` jsdoc promised: read once as text, try
				// JSON.parse, fall back to the raw string. Empty body
				// becomes null so `instanceof` checks stay clean.
				const raw = await res.text();
				let body: unknown = null;
				if (raw.length > 0) {
					try {
						body = JSON.parse(raw);
					} catch {
						body = raw;
					}
				}
				const message = typeof body === "string" ? body : res.statusText;
				throw fireError(new RpcError(`HTTP_${res.status}`, res.status, body as never, message));
			}
			try {
				return (await res.json()) as T;
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("BAD_BODY", res.status, null, msg));
			}
		},
		listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn {
			const sock = ensureWs();
			let set = subs.get(topic);
			const isFirst = !set;
			if (!set) {
				set = new Set();
				subs.set(topic, set);
			}
			const wrapped = handler as (p: unknown) => void;
			set.add(wrapped);
			// First listener for this topic asks the server to start sending
			// it. On a not-yet-open socket the `open` handler resubscribes
			// everything, so only send now if it's already connected.
			if (isFirst && sock.readyState === WebSocket.OPEN) {
				sock.send(JSON.stringify({ type: "subscribe", topic }));
			}
			return () => {
				set!.delete(wrapped);
				if (set!.size === 0) {
					subs.delete(topic);
					// Last listener gone: stop the server sending this topic.
					if (ws && ws.readyState === WebSocket.OPEN) {
						ws.send(JSON.stringify({ type: "unsubscribe", topic }));
					}
				}
				if (subs.size === 0 && reconnectTimer) {
					clearTimeout(reconnectTimer);
					reconnectTimer = undefined;
				}
			};
		},
		onOpen(handler: () => void): UnlistenFn {
			openHandlers.add(handler);
			// Already connected? Fire immediately so callers don't miss the
			// current session.
			if (ws && ws.readyState === WebSocket.OPEN) handler();
			return () => { openHandlers.delete(handler); };
		},
		send(frame: Record<string, unknown>): void {
			rawSend(frame);
		},
		onError(handler: (err: RpcError) => void): UnlistenFn {
			errorHandlers.add(handler);
			return () => { errorHandlers.delete(handler); };
		},
	};
}
