//! Rust emit: writes `_generated.rs` (axum router + event emitters).

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use super::config::Config;
use super::model::{Api, EventApi};
use super::types::result_ok_type;
use super::util::{capitalize, last_path_segment, snake_to_camel};
use super::writer::Writer;

// `include_generated!(MyState, MyBus)` wraps the include in a module
// that aliases these internal names to the caller's actual types, so
// the emitted file doesn't need to know where the state lives.
const STATE_TY: &str = "__DraadState";
const BUS_TY: &str = "__DraadBus";

pub(super) fn write_generated_rs(
    cfg: &Config,
    out_path: &Path,
    apis: &[Api],
    event_apis: &[EventApi],
) -> std::io::Result<()> {
    let mut w = Writer::new("    ");

    write_header(&mut w, cfg);
    write_module_uses(&mut w, cfg, apis, event_apis);

    for api in apis {
        for method in &api.methods {
            write_method_args_struct(&mut w, method);
            write_method_handler(&mut w, api, method);
        }
    }

    write_rpc_router(&mut w, apis);
    write_event_emitters(&mut w, event_apis);

    let out = w.into_string();
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    if let Ok(existing) = fs::read_to_string(out_path) {
        if existing == out {
            return Ok(());
        }
    }
    fs::write(out_path, out)
}

fn write_header(w: &mut Writer, cfg: &Config) {
    w.line("// Generated by draad-codegen. Do not edit.");
    w.line("// Include via `draad::include_generated!(StateTy, BusTy)`.");
    w.blank();
    w.line("use axum::extract::{Query, State};");
    w.line("use axum::routing::{delete, get, patch, post, put};");
    w.line("use axum::{Json, Router};");
    w.line(&format!("use {};", cfg.rpc_runtime_use));
    w.blank();
}

fn write_module_uses(w: &mut Writer, cfg: &Config, apis: &[Api], event_apis: &[EventApi]) {
    let mut modules: BTreeSet<&str> = BTreeSet::new();
    for api in apis {
        modules.insert(api.module.as_str());
    }
    for ev in event_apis {
        modules.insert(ev.module.as_str());
    }
    for module in &modules {
        w.line(&format!(
            "use {prefix}::{module}::*;",
            prefix = cfg.api_modules_prefix
        ));
    }
    if !modules.is_empty() {
        w.blank();
    }
}

fn write_method_args_struct(w: &mut Writer, m: &super::model::Method) {
    if m.params.is_empty() {
        return;
    }
    w.line("#[derive(::serde::Deserialize)]");
    w.line(&format!("struct __{cmd}_args {{", cmd = m.command));
    w.indented(|w| {
        for p in &m.params {
            w.line(&format!("{}: {},", p.name, p.rust_type));
        }
    });
    w.line("}");
    w.blank();
}

fn write_method_handler(w: &mut Writer, api: &Api, m: &super::model::Method) {
    let mut extractors = vec![format!("State(__ctx): State<{STATE_TY}>")];
    if !m.params.is_empty() {
        // Body verbs (POST/PUT/PATCH) take args as a JSON body; non-body
        // verbs (GET/DELETE) take the same args off the query string.
        // The DTO is the same `__{cmd}_args` struct either way.
        let inner = format!("__{cmd}_args", cmd = m.command);
        extractors.push(if m.verb.has_body() {
            format!("Json(__args): Json<{inner}>")
        } else {
            format!("Query(__args): Query<{inner}>")
        });
    }

    let call_args = if m.params.is_empty() {
        String::new()
    } else {
        let names: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("__args.{}", p.name))
            .collect();
        format!(", {}", names.join(", "))
    };

    w.line(&format!(
        "async fn __{cmd}({extractors}) -> Response<{ok}> {{",
        cmd = m.command,
        extractors = extractors.join(", "),
        ok = result_ok_type(m.returns_result, &m.ret_rust),
    ));
    w.indented(|w| {
        let call = format!(
            "<{STATE_TY} as {trait_name}>::{method}(&__ctx{call_args}).await",
            trait_name = api.class_name,
            method = m.rust_name,
        );
        if m.returns_result {
            w.line(&format!("ok({call})"));
        } else {
            w.line(&format!("Response(Ok({call}))"));
        }
    });
    w.line("}");
    w.blank();
}

fn write_rpc_router(w: &mut Writer, apis: &[Api]) {
    w.line(&format!("pub fn rpc_router() -> Router<{STATE_TY}> {{"));
    w.indented(|w| {
        w.line("Router::new()");
        w.indented(|w| {
            for api in apis {
                for m in &api.methods {
                    w.line(&format!(
                        ".route(\"/{ns}/{name}\", {verb_fn}(__{cmd}))",
                        ns = api.namespace,
                        name = m.rust_name,
                        verb_fn = m.verb.axum_fn(),
                        cmd = m.command,
                    ));
                }
            }
        });
    });
    w.line("}");
    w.blank();
}

fn write_event_emitters(w: &mut Writer, event_apis: &[EventApi]) {
    for ev in event_apis {
        let pascal = capitalize(&snake_to_camel(&ev.namespace));
        w.line("#[derive(Clone)]");
        w.line(&format!("pub struct {pascal}Emitter {{ bus: {BUS_TY} }}"));
        w.blank();
        w.line(&format!("impl {pascal}Emitter {{"));
        w.indented(|w| {
            for e in &ev.events {
                let payload = last_path_segment(&e.payload_rust);
                w.line(&format!(
                    "/// Publishes the `{wire}` event to all WS subscribers.",
                    wire = e.wire
                ));
                w.line(&format!(
                    "pub fn emit_{name}(&self, payload: &{payload}) {{",
                    name = e.rust_name,
                ));
                w.indented(|w| {
                    w.line(&format!(
                        "self.bus.publish(\"{wire}\", payload);",
                        wire = e.wire
                    ));
                });
                w.line("}");
            }
        });
        w.line("}");
        w.blank();
    }

    w.line("#[derive(Clone)]");
    w.line("pub struct Events {");
    w.indented(|w| {
        for ev in event_apis {
            let pascal = capitalize(&snake_to_camel(&ev.namespace));
            w.line(&format!("pub {ns}: {pascal}Emitter,", ns = ev.namespace));
        }
    });
    w.line("}");
    w.blank();

    w.line("impl Events {");
    w.indented(|w| {
        let bus_param = if event_apis.is_empty() { "_bus" } else { "bus" };
        w.line(&format!("pub fn new({bus_param}: {BUS_TY}) -> Self {{"));
        w.indented(|w| {
            w.line("Self {");
            w.indented(|w| {
                for ev in event_apis {
                    let pascal = capitalize(&snake_to_camel(&ev.namespace));
                    w.line(&format!(
                        "{ns}: {pascal}Emitter {{ bus: bus.clone() }},",
                        ns = ev.namespace
                    ));
                }
            });
            w.line("}");
        });
        w.line("}");
    });
    w.line("}");
}
