//! Rust emit: writes `_generated.rs` (axum router + event emitters).

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use super::config::Config;
use super::model::{Api, EventApi};
use super::parse::snake_to_camel;

pub(super) fn write_generated_rs(
    cfg: &Config,
    out_path: &Path,
    apis: &[Api],
    event_apis: &[EventApi],
) -> std::io::Result<()> {
    // The state/bus types are the internal names `__DraadState` /
    // `__DraadBus`. `draad::include_generated!(MyState, MyBus)` wraps the
    // include in a module that aliases those names to the caller's
    // actual types.
    let state_short = "__DraadState";
    let bus_short = "__DraadBus";

    let mut out = String::new();
    out.push_str("// Generated by draad-codegen. Do not edit.\n");
    out.push_str("// Include via `draad::include_generated!(StateTy, BusTy)`.\n\n");
    out.push_str("use axum::extract::State;\n");
    out.push_str("use axum::routing::post;\n");
    out.push_str("use axum::{Json, Router};\n");
    out.push_str(&format!("use {};\n\n", cfg.rpc_runtime_use));

    let mut modules_used: BTreeSet<String> = BTreeSet::new();
    for api in apis {
        modules_used.insert(api.module.clone());
    }
    for ev in event_apis {
        modules_used.insert(ev.module.clone());
    }
    for module in &modules_used {
        out.push_str(&format!(
            "use {prefix}::{module}::*;\n",
            prefix = cfg.api_modules_prefix
        ));
    }
    if !modules_used.is_empty() {
        out.push('\n');
    }

    for api in apis {
        for m in &api.methods {
            if !m.params.is_empty() {
                out.push_str("#[derive(::serde::Deserialize)]\n");
                out.push_str(&format!("struct __{cmd}_args {{\n", cmd = m.command));
                for p in &m.params {
                    out.push_str(&format!("    {}: {},\n", p.name, p.rust_type));
                }
                out.push_str("}\n\n");
            }

            let mut extractors = vec![format!("State(__ctx): State<{state_short}>")];
            if !m.params.is_empty() {
                extractors.push(format!("Json(__args): Json<__{cmd}_args>", cmd = m.command));
            }

            let call_args = if m.params.is_empty() {
                String::new()
            } else {
                let names: Vec<String> = m
                    .params
                    .iter()
                    .map(|p| format!("__args.{}", p.name))
                    .collect();
                format!(", {}", names.join(", "))
            };

            out.push_str(&format!(
                "async fn __{cmd}({extractors}) -> Response<{ok}> {{\n",
                cmd = m.command,
                extractors = extractors.join(", "),
                ok = m.ret_rust_ok(),
            ));

            if m.returns_result {
                out.push_str(&format!(
                    "    ok(<{state} as {trait_name}>::{method}(&__ctx{call_args}).await)\n",
                    state = state_short,
                    trait_name = api.class_name,
                    method = m.rust_name,
                ));
            } else {
                out.push_str(&format!(
                    "    Response(Ok(<{state} as {trait_name}>::{method}(&__ctx{call_args}).await))\n",
                    state = state_short,
                    trait_name = api.class_name,
                    method = m.rust_name,
                ));
            }
            out.push_str("}\n\n");
        }
    }

    out.push_str(&format!(
        "pub fn rpc_router() -> Router<{state_short}> {{\n"
    ));
    out.push_str("    Router::new()\n");
    for api in apis {
        for m in &api.methods {
            out.push_str(&format!(
                "        .route(\"/{ns}/{name}\", post(__{cmd}))\n",
                ns = api.namespace,
                name = m.rust_name,
                cmd = m.command,
            ));
        }
    }
    out.push_str("}\n\n");

    write_emit_impls(&mut out, event_apis, bus_short);

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    if let Ok(existing) = fs::read_to_string(out_path) {
        if existing == out {
            return Ok(());
        }
    }
    fs::write(out_path, out)
}

fn write_emit_impls(out: &mut String, event_apis: &[EventApi], bus_short: &str) {
    for ev in event_apis {
        let pascal = capitalize(&snake_to_camel(&ev.namespace));
        out.push_str("#[derive(Clone)]\n");
        out.push_str(&format!(
            "pub struct {pascal}Emitter {{ bus: {bus_short} }}\n\n"
        ));
        out.push_str(&format!("impl {pascal}Emitter {{\n"));
        for e in &ev.events {
            let payload = last_path_segment(&e.payload_rust);
            out.push_str(&format!(
                "    /// Publishes the `{wire}` event to all WS subscribers.\n",
                wire = e.wire
            ));
            out.push_str(&format!(
                "    pub fn emit_{name}(&self, payload: &{payload}) {{\n",
                name = e.rust_name,
            ));
            out.push_str(&format!(
                "        self.bus.publish(\"{wire}\", payload);\n",
                wire = e.wire,
            ));
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }

    out.push_str("#[derive(Clone)]\n");
    out.push_str("pub struct Events {\n");
    for ev in event_apis {
        let pascal = capitalize(&snake_to_camel(&ev.namespace));
        out.push_str(&format!(
            "    pub {ns}: {pascal}Emitter,\n",
            ns = ev.namespace
        ));
    }
    out.push_str("}\n\n");

    out.push_str("impl Events {\n");
    let bus_param = if event_apis.is_empty() { "_bus" } else { "bus" };
    out.push_str(&format!(
        "    pub fn new({bus_param}: {bus_short}) -> Self {{\n"
    ));
    out.push_str("        Self {\n");
    for ev in event_apis {
        let pascal = capitalize(&snake_to_camel(&ev.namespace));
        out.push_str(&format!(
            "            {ns}: {pascal}Emitter {{ bus: bus.clone() }},\n",
            ns = ev.namespace
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
}

pub(super) fn last_path_segment(rust_ty: &str) -> String {
    if rust_ty.contains('<') {
        return rust_ty.to_string();
    }
    // Strip `{X, Y}` group syntax, e.g. `crate::rpc::{Response, ok}`
    // shouldn't be reduced to a single segment.
    let plain = rust_ty
        .split('{')
        .next()
        .unwrap_or(rust_ty)
        .trim_end_matches("::");
    plain.rsplit("::").next().unwrap_or(plain).to_string()
}

pub(super) fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}
