//! TypeScript emit: writes a single `index.ts` containing the transport
//! interface, every wire type, the per-namespace classes, and the `Api`
//! aggregator.

use std::fs;
use std::path::Path;

use super::model::{Api, EventApi, Param, Verb};
use super::util::{capitalize, normalize_numbers};
use super::writer::Writer;

/// Transport interface, error type, and a default REST+WS `Rpc`
/// implementation embedded at the top of every generated `index.ts`.
///
/// Source lives in `rpc_runtime.ts` next to this file — edit it there
/// and rely on syntax highlighting / formatters instead of escaping the
/// file into a Rust string literal.
const RPC_RUNTIME_TS: &str = include_str!("rpc_runtime.ts");

pub(super) fn write_index(
    out_path: &Path,
    types_in_order: &[String],
    per_type_dir: &Path,
    apis: &[Api],
    event_apis: &[EventApi],
) -> std::io::Result<()> {
    let mut w = Writer::new("\t");

    w.line("// Generated by draad-codegen. Do not edit.");
    w.blank();
    w.raw(RPC_RUNTIME_TS);

    inline_type_bindings(&mut w, types_in_order, per_type_dir);

    for api in apis {
        write_api_class(&mut w, api);
    }
    for ev in event_apis {
        write_events_class(&mut w, ev);
    }

    write_aggregator(&mut w, apis, event_apis);

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    let out = w.into_string();
    // Skip the write if the file already matches — otherwise we'd bump
    // its mtime on every build, which combined with the
    // `cargo:rerun-if-changed=index.ts` directive emit_cargo_directives
    // prints would trap the build script in an infinite re-run loop.
    if let Ok(existing) = fs::read_to_string(out_path) {
        if existing == out {
            return Ok(());
        }
    }
    fs::write(out_path, out)
}

/// Inline ts-rs's per-type bindings into the unified `index.ts`. Each
/// type's file is dropped in verbatim (modulo import lines and the
/// generated-by header), preceded by a separator blank line.
fn inline_type_bindings(w: &mut Writer, types_in_order: &[String], per_type_dir: &Path) {
    for ty in types_in_order {
        w.blank();
        let file = per_type_dir.join(format!("{ty}.ts"));
        let raw = fs::read_to_string(&file).unwrap_or_else(|_| {
            panic!(
                "missing per-type binding {}, run `cargo test export_bindings` first",
                file.display()
            );
        });
        for line in raw.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("import ") || trimmed.starts_with("// This file was generated") {
                continue;
            }
            // The per-type files already carry their own indentation;
            // splice them in at column 0 rather than letting the Writer's
            // indent level re-indent them.
            w.raw(&normalize_numbers(line));
            w.raw("\n");
        }
    }
}

fn write_api_class(w: &mut Writer, api: &Api) {
    w.blank();
    write_jsdoc(w, &api.docs);
    w.line(&format!("export class {} {{", api.class_name));
    w.indented(|w| {
        w.line("constructor(private rpc: Rpc) {}");
        for m in &api.methods {
            write_api_method(w, api, m);
        }
    });
    w.line("}");
}

fn write_api_method(w: &mut Writer, api: &Api, m: &super::model::Method) {
    let param_decl = m
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.ts_type))
        .collect::<Vec<_>>()
        .join(", ");

    // POST is the implicit default so emit `call("ns/name", { args })`
    // verbatim — keeps existing generated TS byte-identical. For other
    // verbs we always pass an args object (even `{}`) so the verb sits
    // in the third slot.
    let args_obj = if m.params.is_empty() {
        "{}".to_string()
    } else {
        let names = m
            .params
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        format!("{{ {names} }}")
    };
    let call_tail = if m.verb == Verb::Post {
        if m.params.is_empty() {
            String::new()
        } else {
            format!(", {args_obj}")
        }
    } else {
        format!(", {args_obj}, \"{verb}\"", verb = m.verb.ts_label())
    };

    w.blank();
    write_method_jsdoc(w, &m.docs, &m.params);
    w.line(&format!(
        "{name}({decl}): Promise<{ret}> {{",
        name = m.ts_name,
        decl = param_decl,
        ret = m.ret_ts,
    ));
    w.indented(|w| {
        w.line(&format!(
            "return this.rpc.call(\"{ns}/{name}\"{call_tail});",
            ns = api.namespace,
            name = m.rust_name,
        ));
    });
    w.line("}");
}

fn write_events_class(w: &mut Writer, ev: &EventApi) {
    w.blank();
    write_jsdoc(w, &ev.docs);
    w.line(&format!("export class {} {{", ev.class_name));
    w.indented(|w| {
        w.line("constructor(private rpc: Rpc) {}");
        for e in &ev.events {
            w.blank();
            write_jsdoc(w, &e.docs);
            w.line(&format!(
                "on{cap}(handler: (payload: {pl}) => void): UnlistenFn {{",
                cap = capitalize(&e.ts_name),
                pl = e.payload_ts,
            ));
            w.indented(|w| {
                w.line(&format!(
                    "return this.rpc.listen<{pl}>(\"{wire}\", handler);",
                    pl = e.payload_ts,
                    wire = e.wire,
                ));
            });
            w.line("}");
        }
    });
    w.line("}");
}

fn write_aggregator(w: &mut Writer, apis: &[Api], event_apis: &[EventApi]) {
    w.blank();
    w.line("export class Api {");
    w.indented(|w| {
        for api in apis {
            write_jsdoc(w, &api.docs);
            w.line(&format!(
                "{ns}: {cls};",
                ns = api.namespace,
                cls = api.class_name
            ));
        }
        for ev in event_apis {
            write_jsdoc(w, &ev.docs);
            w.line(&format!(
                "{ns}Events: {cls};",
                ns = ev.namespace,
                cls = ev.class_name
            ));
        }
        w.blank();
        w.line("constructor(rpc: Rpc) {");
        w.indented(|w| {
            for api in apis {
                w.line(&format!(
                    "this.{ns} = new {cls}(rpc);",
                    ns = api.namespace,
                    cls = api.class_name
                ));
            }
            for ev in event_apis {
                w.line(&format!(
                    "this.{ns}Events = new {cls}(rpc);",
                    ns = ev.namespace,
                    cls = ev.class_name
                ));
            }
        });
        w.line("}");
    });
    w.line("}");
}

fn write_jsdoc(w: &mut Writer, docs: &[String]) {
    if docs.is_empty() {
        return;
    }
    if docs.len() == 1 {
        w.line(&format!("/** {} */", docs[0]));
        return;
    }
    w.line("/**");
    for line in docs {
        w.line(&format!(" * {line}"));
    }
    w.line(" */");
}

fn write_method_jsdoc(w: &mut Writer, method_docs: &[String], params: &[Param]) {
    let has_method = !method_docs.is_empty();
    let has_params = params.iter().any(|p| !p.docs.is_empty());
    if !has_method && !has_params {
        return;
    }
    if has_method && !has_params && method_docs.len() == 1 {
        w.line(&format!("/** {} */", method_docs[0]));
        return;
    }
    w.line("/**");
    for line in method_docs {
        w.line(&format!(" * {line}"));
    }
    for p in params {
        if p.docs.is_empty() {
            continue;
        }
        let summary = p.docs.join(" ");
        w.line(&format!(" * @param {} - {summary}", p.name));
    }
    w.line(" */");
}
