//! Exercises the `#[ty]` → per-type-binding → inlined-into-`index.ts`
//! pipeline. ts-rs would normally write the per-type files during
//! `cargo test export_bindings`; here we fake those files so the test is
//! self-contained.

#![cfg(feature = "codegen")]

mod common;

#[test]
fn inlines_wire_types_into_index_ts() {
    let root = common::fresh_root("ts-types");

    // The trait method returns a user-defined wire type `Hit` and a
    // primitive `i32`. The `Hit` struct is marked `#[ty]` so the codegen
    // knows to look for a per-type binding for it.
    std::fs::write(
        root.join("src/search.rs"),
        r#"
use draad::{api, ty};

#[ty]
pub struct Hit { pub id: i64, pub title: String }

#[api(namespace = "search")]
pub trait SearchApi {
    /// Full-text search.
    async fn query(&self, q: String) -> Result<Vec<Hit>, MyError>;
    /// Total indexed.
    async fn count(&self) -> i32;
}
"#,
    )
    .unwrap();

    // Fake what ts-rs would emit during `cargo test export_bindings`.
    // The codegen reads from `per_type_dir/_per_type/<TypeName>.ts` and
    // inlines the body (minus imports / generated-by comments).
    let per_type_dir = root.join("bindings/_per_type");
    std::fs::create_dir_all(&per_type_dir).unwrap();
    std::fs::write(
        per_type_dir.join("Hit.ts"),
        "// This file was generated by ts-rs.\n\
         export type Hit = { id: bigint, title: string, };\n",
    )
    .unwrap();

    let client_dir = root.join("frontend");
    draad::codegen::Config::new()
        .root(&root)
        .client_dir(&client_dir)
        .per_type_dir(root.join("bindings"))
        .rpc_runtime("draad::runtime::{Response, ok}")
        .generate()
        .unwrap();

    let index = std::fs::read_to_string(client_dir.join("index.ts")).expect("index.ts written");

    // Type body inlined, with `bigint` normalised to `number`.
    assert!(
        index.contains("export type Hit = { id: number, title: string, };"),
        "missing inlined Hit type (or bigint→number normalization):\n{index}"
    );

    // ts-rs's generated-by comment is stripped during inlining.
    assert!(
        !index.contains("This file was generated by ts-rs"),
        "ts-rs comment should be stripped:\n{index}"
    );

    // Method signature references the user type by bare name (everything
    // lives in the same file).
    assert!(
        index.contains("query(q: string): Promise<Hit[]>"),
        "missing typed return signature:\n{index}"
    );
    assert!(
        index.contains("count(): Promise<number>"),
        "missing primitive-return signature:\n{index}"
    );

    // The wire route remains `namespace/method`.
    assert!(
        index.contains("return this.rpc.call(\"search/query\""),
        "missing wire path:\n{index}"
    );
}
